apiVersion: v1
kind: Service
metadata:
  name: leverage-analyzer-service
spec:
  selector:
    app: leverage-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
